apiVersion: 1
datasources:
  - name: HealthSave
    uid: healthsave-pg
    type: postgres
    url: ${HDH_GRAFANA_DATASOURCE_URL}
    user: healthsave
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: healthsave
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    isDefault: true
    editable: true
