"""Convenience guard (SECURITY-005 follow-up): every compose-REQUIRED secret
(``${VAR:?...}``) must be generated by setup.sh and documented in .env.example,
so the easy path -- run setup.sh, then `docker compose up` -- always works
without manual edits. This prevents adding a new required var to compose while
forgetting to make it easy to set.
"""

from __future__ import annotations

import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]


def _required_compose_vars() -> set[str]:
    text = (_ROOT / "docker-compose.yml").read_text()
    # ${VAR:?...} means compose fails if VAR is unset -- i.e. it is required.
    return set(re.findall(r"\$\{([A-Z0-9_]+):\?", text))


def test_there_is_at_least_one_required_secret():
    # Sanity: the parser actually finds the required vars it is meant to guard.
    assert {"DB_PASSWORD", "GRAFANA_PASSWORD"} <= _required_compose_vars()


def test_required_compose_vars_are_generated_by_setup():
    required = _required_compose_vars()
    setup = (_ROOT / "setup.sh").read_text()
    missing = [v for v in required if f"{v}=" not in setup]
    assert missing == [], f"setup.sh does not write required compose vars: {missing}"


def test_required_compose_vars_are_documented_in_env_example():
    required = _required_compose_vars()
    env_example = (_ROOT / ".env.example").read_text()
    missing = [v for v in required if f"{v}=" not in env_example]
    assert missing == [], f".env.example is missing required compose vars: {missing}"
